format = """
[\ue0ca ](#FFEA00)\
[  ](bg:#FFEA00 fg:#C70039)\
$os\
$username\
[\ue0c0 ](bg:#FFBF00 fg:#FFEA00)\
$directory\
[\ue0c0 ](fg:#FFBF00 bg:#FF5733 )\
$git_branch\
$git_status\
[\ue0c0 ](fg:#FF5733  bg:#C70039 )\
$php\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[\ue0c0 ](fg:#C70039  bg:#900C3F)\
$docker_context\
[\ue0c0 ](fg:#900C3F bg:#581845 )\
$time\
[\ue0c0 ](fg:#581845)\
"""

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#FFEA00 fg:#090c0c"
style_root = "bg:#FFEA00 fh:#090c0c"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#FFBF00 fg:#090c0c"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#C70039  fg:#090c0c"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#900C3F fg:#090c0c"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#C70039 fg:#090c0c"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#C70039 fg:#090c0c"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FF5733 fg:#090c0c"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FF5733 fg:#090c0c"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#C70039 fg:#090c0c"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#C70039 fg:#090c0c"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#C70039 fg:#090c0c"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#C70039 fg:#090c0c"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#C70039 fg:#090c0c"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#C70039  fg:#090c0c"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#C70039 fg:#090c0c"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#C70039 fg:#090c0c"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#C70039 fg:#090c0c"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
style = "bg:#C70039 fg:#090c0c"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#581845 fg:#090c0c"
format = '[[  $time ](fg:#ffffff bg:#581845)]($style)'

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
# add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
